using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Linq.Expressions;
using System.Text;


namespace FastPropertyAccess.Generator
{
    [Generator]
    public class PropertyAccessSourceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {

            var methodCalls = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (s, _) => s is InvocationExpressionSyntax,
                    transform: (ctx, _) => GetInvocationDetails(ctx))
                .Where(m => m is not null);

            var collectedCalls = methodCalls.Collect();

            context.RegisterHostOutput(collectedCalls, GenerateSource);
        }

        private InvocationDetails? GetInvocationDetails(GeneratorSyntaxContext context)
        {
            var invocation = (InvocationExpressionSyntax)context.Node;

            if(invocation.Expression is MemberAccessExpressionSyntax memberAccess &&
                memberAccess.Expression is IdentifierNameSyntax className &&
                className.Identifier.Text == "PropertyCahe")
            {
                var methodSymbol = context.SemanticModel.GetSymbolInfo(invocation).Symbol as IMethodSymbol;

                if (methodSymbol?.Name == "GetGetter" && methodSymbol.IsGenericMethod)
                {
                    var typeArgs = methodSymbol.TypeArguments;
                    var propertyNameArg = invocation.ArgumentList.Arguments.FirstOrDefault()?.Expression;

                    string? propertyName = null;
                    if (propertyNameArg is LiteralExpressionSyntax literal &&
                        literal.IsKind(SyntaxKind.StringLiteralToken))
                    {
                        propertyName = literal.Token.ValueText;
                    }

                    if(typeArgs.Length == 2 && propertyName != null)
                    {
                        return new InvocationDetails(
                            ContainingType: methodSymbol.ContainingType,
                            PropertyType: typeArgs[0],
                            PropertyReturnType: typeArgs[1],
                            PropertyName: propertyName);
                    }
                }
            }
            return null;
        }

        private void GenerateSource(SourceProductionContext context, ImmutableArray<InvocationDetails> invocations)
        {
            if (invocations.IsDefaultOrEmpty)
            {
                return;
            }

            var grouppedInvocations = invocations
                .GroupBy(i => i.PropertyType)
                .ToDictionary(g => g.Key, g => g.ToList());

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            var namespaceName = invocations.First().ContainingType.ContainingNamespace.ToDisplayString();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine("    public static class PropertyCacheGenerated");
            sb.AppendLine("    {");
            foreach (var invocation in invocations.Distinct().Where(i => i is not null))
            {
                sb.AppendLine($"        public static Func<{invocation!.PropertyType.ToDisplayString()}, {invocation.PropertyReturnType.ToDisplayString()}> GetGetter_{invocation.ContainingType.Name}_{invocation.PropertyName}() ");
                sb.AppendLine("        {");
                sb.AppendLine($"            return source => source.{invocation.PropertyName};");
                sb.AppendLine("        }");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");
            context.AddSource("PropertyCacheGenerated.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private record InvocationDetails(INamedTypeSymbol ContainingType, ITypeSymbol PropertyType, 
                                        ITypeSymbol PropertyReturnType, string PropertyName);
    }
}
